FROM            eb-docker:base
MAINTAINER      dosio0102@gmail.com

ENV             BUILD_MODE  dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt

COPY            .       /srv/Brunch-RSSFeed