FROM            eb-docker:base
MAINTAINER      dosio0102@gmail.com

COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt

COPY            .       /srv/Brunch-RSSFeed