# Generated by Django 2.1.5 on 2019-01-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('article_txid', models.CharField(max_length=200, unique=True, verbose_name='작가id_글번호')),
                ('published_time', models.DateTimeField()),
                ('text_id', models.IntegerField(verbose_name='글 번호')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, null=True, verbose_name='검색 단어')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True, verbose_name='작가ID')),
                ('media_name', models.CharField(max_length=200, verbose_name='작가명')),
                ('num_subscription', models.IntegerField(null=True, verbose_name='구독자 수')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(related_name='articles', to='articles.Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Writer'),
        ),
    ]
