# Generated by Django 2.1.4 on 2019-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('href', models.CharField(max_length=200, unique=True, verbose_name='링크 조각')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=200, verbose_name='검색 단어')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(related_name='article', to='articles.Keyword'),
        ),
    ]
