# Generated by Django 2.2.1 on 2019-06-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='media_name',
            field=models.CharField(max_length=200, null=True, verbose_name='작가명'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='user_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='아이디'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True, verbose_name='아이디')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='articles.Writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
