# Generated by Django 2.2 on 2019-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_writer_following_+', to='articles.Writer'),
        ),
    ]
