# Generated by Django 2.1.4 on 2019-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='name',
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=300, verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='keyword',
            field=models.CharField(max_length=50, verbose_name='키워드'),
        ),
    ]
