# Generated by Django 2.1.4 on 2019-01-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='작가ID')),
                ('media_name', models.CharField(max_length=200, verbose_name='작가명')),
            ],
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='search_word',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='article',
            name='media_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(related_name='articles', to='articles.Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Writer'),
            preserve_default=False,
        ),
    ]
