# Generated by Django 2.2 on 2019-04-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_writer_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='media_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='작가명'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='num_subscription',
            field=models.IntegerField(blank=True, null=True, verbose_name='구독자 수'),
        ),
    ]
