# Generated by Django 2.1.4 on 2019-01-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190102_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
