FROM            brunch-rss-feed:base
MAINTAINER      dosio0102@gmail.com

#COPY            ./requirements.txt  /srv/
#RUN             pip install -r /srv/requirements.txt

ENV             BUILD_MODE  dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            .       /srv/Brunch-RSS-Feed

# nginx 설정파일을 미리 준비해둔 파일로 바꿔준다
            # user root, daemon off 설정이 들어간 '기본' 설정
RUN         cp -f   /srv/Brunch-RSS-Feed/.config/${BUILD_MODE}/nginx.conf \
                    /etc/nginx/nginx.conf && \
            # nginx 가 사용할 site 로 내 앱 설정을 넣어준다.(socket, port 설정)
            cp -f   /srv/Brunch-RSS-Feed/.config/${BUILD_MODE}/nginx_app.conf \
                    /etc/nginx/sites-available/ && \
            # 이전에 설정해놓은 파일 삭제
            rm -f   /etc/nginx/sites-enabled/* && \
            # enabled 로 링크 생성 및 완료
            ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                    /etc/nginx/sites-enabled/

# supervisor 셋팅 해준다
RUN         cp -f   /srv/Brunch-RSS-Feed/.config/${BUILD_MODE}/supervisor_app.conf \
                    /etc/supervisor/conf.d/

# supervisord -n 명령어는 .config/supervisor_app.conf 의 명령어를 수행한다
CMD         supervisord -n
